[package]
name = "rust-web"
version = "0.1.0"
authors = ["John Webb <John.Webb94@gmail.com>"]
description = "Simple rust visualizer"
repository = "TBD"
edition = "2018"

[lib]
crate-type = ['cdylib']

[dependencies]
wasm-bindgen = '0.2'
